### PR TITLE
Add features

### PR DESCRIPTION
**Pull request by samuel-w**
See commit messages.

### CODE REVIEW

**Comment by Proxtx** [comment]
The load function currently writes undefined or null to the element values if there hasn't been set anything yet. I would recommend this syntax: `localStorage.lineSpacing && lineSpacingElem.value = localStorage.lineSpacing`.
Besides from that... Great pull request.

**Comment by samuel-w** [comment]
Fixed it.

**Comment by Proxtx** [comment]
the problem with using the nativ resolution is, that the font-size works independent of the image size. The text could become very small or huge and many users don't know how to change the font-size.

**Comment by samuel-w** [comment]
Would a checkbox of "Keep original image resolution" work?

**Comment by Proxtx** [comment]
Yeah that would work

**Pull request merged**
